version: '3.2'

services:
  db:
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: task_1
      POSTGRES_PASSWORD: task_1

volumes:
  postgres_data: